version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_DB=ac_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ac_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c 'max_connections=1000' -c 'shared_buffers=256MB' -c 'max_wal_size=1GB'
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: adel@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12054801
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - type: bind
        source: ./backend
        target: /code
      - type: bind
        source: ./backend/staticfiles
        target: /code/staticfiles
      - type: bind
        source: ./backend/media
        target: /code/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-w@p+fa&&omp^oa7&n68==+0@4^+lert43yw8v8yjhrxip821po
      - ALLOWED_HOSTS=localhost,127.0.0.1,159.69.87.39,nasbfix.ir
      - DATABASE_URL=postgres://postgres:admin123@db:5432/ac_db
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - POSTGRES_DB=ac_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    depends_on:
      db:
        condition: service_healthy
    restart: always
#Why???
volumes:
  postgres_data:
    name: ac_service_postgres_data
    driver: local
